version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/var/www/html:rw
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - 90:80
